name: Run Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15, 18.x]
        mongodb-version: [4.4]
        rabbitmq-version: ['3.8.2-management-alpine']
        redis-version: [7]

    steps:
      - uses: actions/checkout@v3

      - name: ğŸŸ¢ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ¦– Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: ${{ matrix.mongodb-version }}

      - name: ğŸ° Launch RabbitMQ
        uses: nijel/rabbitmq-action@v1.0.0
        with:
          rabbitmq version: ${{ matrix.rabbitmq-version }}

      - name: ğŸŸ¥  Launch Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
          
      - name: ğŸ”§ Install dependencies npm
        run: |
          npm install
      
      - name: ğŸƒ Start test npm
        run: |
          npm test
      - name: âœŒï¸ Finish
        run: echo "Push to - ${{github.workflow}} by ${{github.actor}}"