name: Run Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: ğŸŸ¢ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ”§ Install dependencies npm
        run: |
          npm install
      
      - name: âœ… Start test npm
        run: |
          npm test
      - name: âœŒï¸ Finish
        run: echo "Push to - ${{github.workflow}} by ${{github.actor}}"